apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubedx.fullname" . }}
  labels:
    app: {{ template "kubedx.name" . }}
    chart: {{ template "kubedx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubedx.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubedx.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if .Values.appDebug }}
          command: ["java"]
          args: ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005","-jar","/kubedx.jar"]
          {{- end }}
          ports:
            {{- if .Values.appDebug }}
            - name: java-debug
              containerPort: 5005
              protocol: TCP
            {{- end }}
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuvator/health
              port: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
