[environments]
  [environments.development]
    name = "rest-api"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = true
    dockerfile = "Dockerfile"
    chart = ""
    override-ports = ["8080:8080"]
